### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by anjalibhavan** [krumo/emodbSER#4]
Hi,
So I studied your code in detail and had a few issues. Kindly do clarify.
1. You haven't extracted any features like mfcc, chromatic features etc from the speech data right? Isn't it kinda necessary to analyse emotions in speech?
2. Without any extracted features (as per your original code), I printed the first few rows and columns of the 'data' set, and all the entries were zero. Which shows that every entry is zero, because nothing was really extracted from the speech! Hence the low accuracy (possibly): because the model doesn't actually have anything except zeros to train. 
Kindly clarify these points. Thanks.

**Comment by krumo** [comment]
@anjali-123b Thank you for your interest.
1. No, I didn't try to extract any hand-craft features. This project intends to learn an end-to-end model for speech emotion recognition. So the feature extraction process is integrated to neural network. Plus, I think it's still an open question about whether end-to-end model could work in speech emotion classification task. Please feel free to add any feature extraction module for your specific application.
2. You're right, it's a bug of reading_data file.  Now this bug has been fixed in the latest commit. Thanks for pointing it out!
